spring.application.name=tftbiblioteca

# Server settings
server.port=8070
spring.data.rest.basePath=/api

# H2 settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.driverClassName=org.h2.Driver

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:tftbiblioteca
# Alternatively, you can use a database persisted on the filesystem
# spring.datasource.url=jdbc:h2:file:./data/tftbiblioteca
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

springdoc.swagger-ui.disable-swagger-default-url=true
